### ISSUE TITLE
Model unable to run due to incorrect number of dimesions

### ISSUE THREAD

**Issue by zbartolek** [statdivlab/enviromtx#12]
I noticed that the model fails in some cases when I remove incomplete and missing samples (the total number of samples changes, as a result of removing one or more replicate samples from the dataset). I get a "incomplete number of dimensions" error. Here are two examples, one that runs well with the full set of samples used (G1_example_all_samples.csv), and one that fails when I remove missing samples (G1_example_removed_missing_samples.csv). 

Thanks!! 
[G1_example_all_samples.csv](https://github.com/user-attachments/files/17496273/G1_example_all_samples.csv)
[G1_example_removed_missing_samples.csv](https://github.com/user-attachments/files/17496275/G1_example_removed_missing_samples.csv)

**Comment by svteichman** [comment]
Hi Zinka,

Thanks for sending these examples over! I'll take a look and see if I can see where this error is coming from when you remove samples. 

Sarah

**Comment by svteichman** [comment]
@zbartolek could you also provide the code that you are running that leads to this error?

**Comment by zbartolek** [comment]
Yes, here is the script I use. Thanks Sarah! 
```

library(plyr)
library(dplyr)

library(tidyr)
library(stringr)
library(data.table)
library(ggplot2)
library(splitstackshape)
library(gtools)
library(lsr)
library(tictoc)

library(here) # for file paths
library(R.utils)

remotes::install_github("statdivlab/raoBust")
remotes::install_github("statdivlab/enviromtx")
library(enviromtx)
library(geeasy)


pair_data_funct <- read.csv("~/Desktop/G1_example_removed_all_samples.csv")
pair_data_funct <- read.csv("~/Desktop/G1_example_removed_missing_samples.csv")

temp <- pair_data_funct$temp
NO3_NO2_uM <- pair_data_funct$NO3_NO2_uM
Mn_nM <- pair_data_funct$Mn_nM

##### Run the Model:
try({out_i_k <- fit_mgx_model(
  yy = pair_data_funct$counts_sum,
  xstar = pair_data_funct$xstar,
  xx = pair_data_funct$xx,
  formula = ~ temp, # ~temperature + Fe_nM + NO3_NO2_uM + PO4_uM + SiO4_uM + Zn_nM + Cd_pM + Ni_nM + Cu_nM + Pb_pM + Mn_nM + Co_pM #Environemntal co-variates
  enviro_df = cbind(temp, NO3_NO2_uM, Mn_nM),
  replicates = pair_data_funct$sample_name,
  wts = NULL,
  replace_zeros = "minimum")})
```

**Comment by svteichman** [comment]
@zbartolek great news - this was a pretty easy fix! The issue was that one of the functions in `raoBust`, which `enviromtx` depends on expected all clusters to have more than one observation, so there was an issue with indexing. I believe that that's all fixed with a pull request to `raoBust` that I just merged, and that with this fix your example should run. Could you please re-install `raoBust` with`remotes::install_github("statdivlab/raoBust")` and then re-run your analysis. Let me know if it is still running into an error!

**Comment by zbartolek** [comment]
Hi Sarah, thanks a lot! Glad its an easy fix :) I just tried running the failing sample, and I still get the same error (Error in xxi[j, k] : incorrect number of dimensions). I re-installed raoBust, and I'm using the same code as above. Maybe it's something on my end, I'm not sure. Were you able to run the failing sample?

**Comment by svteichman** [comment]
Shoot! I thought I had it working on my end but I’ll double check tomorrow  On Oct 23, 2024, at 9:15 PM, zbartolek ***@***.***> wrote:﻿
Hi Sarah, thanks a lot! Glad its an easy fix :) I just tried running the failing sample, and I still get the same error (Error in xxi[j, k] : incorrect number of dimensions). I re-installed raoBust, and I'm using the same code as above. Maybe it's something on my end, I'm not sure. Were you able to run the failing sample?

**Comment by svteichman** [comment]
@zbartolek on my end it runs. Sometimes I find that packages from github, even after I install new versions, take a little while to update. Could you try to open and close your R session? After that, if it still doesn't work, could you run the code `raoBust::robust_score_test` in your console (don't let R add open and closed parentheses like it wants to do). This should output code for a function. Could you copy that here, so I can check whether that function is correctly updated on your end? 

Thanks!
Sarah

**Comment by zbartolek** [comment]
Hi Sarah, yes I just got it to run too, thank you!! I just opened a new R session and it's working. Sorry about the confusion and thanks so much for the help! Also I heard you are defending soon, congrats :)

**Comment by svteichman** [comment]
Great, I'm glad it's running for you now! And thanks :)
